version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - broker
      - redis
      - es01
      - es02
  
  db:
    image: postgres:15-alpine3.18
    volumes:
      - e_shop_postgres_data:/var/lib/postgresql/dta/
    environment:
      - POSTGRES_USER=e_shop
      - POSTGRES_PASSWORD=1234e_shop
      - POSTGRES_DB=e_shop_dev

  broker:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
    volumes:
      - e_shop_rabbitmq_data:/var/lib/rabbitmq
      - e_shop_raabbitmq_log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:7.2.3
    # restart: always
    ports:
      - 6379:6379

  es01:
      image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        node.name: es01
        discovery.seed_hosts: es01,es02
        cluster.initial_master_nodes: es01,es02
        cluster.name: shop_cluster
        bootstrap.memory_lock: "true"
        ES_JAVA_OPTS: -Xms256m -Xmx256m
      volumes:
        - "es-data-es01:/usr/share/elasticsearch/data"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      healthcheck:
        test: ["CMD-SHELL", "curl http://localhost:9200"]
        interval: 10s
        timeout: 10s
        retries: 120
  es02:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      node.name: es02
      discovery.seed_hosts: es01,es02
      cluster.initial_master_nodes: es01,es02
      cluster.name: shop_cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - "es-data-es02:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200"]'


volumes:
  e_shop_postgres_data:
  e_shop_rabbitmq_data:
  e_shop_raabbitmq_log:
  es-data-es01:
  es-data-es02:

